auto: true

markdown: kramdown
highlighter: rouge
pygments: true
paginate: 8
permalink: /:title

title: bond
url: http://bond.github.io
feed: /atom.xml  
author_info: <a href="http://bond.github.io/">bond</a>
